# Generated by Django 4.2.21 on 2025-05-21 04:21

from django.db import migrations, models
import user.models.demo_user
import user.models.user


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email_enc", models.BinaryField(max_length=1000)),
                ("password_enc", models.BinaryField(max_length=1000)),
                ("name_enc", models.BinaryField(max_length=1000)),
                (
                    "type",
                    models.CharField(
                        choices=[("admin", "管理者"), ("contractor", "法人契約者")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "管理者ユーザ",
                "verbose_name_plural": "管理者ユーザ",
                "db_table": "admin_users",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email_enc", models.BinaryField(max_length=1000)),
                ("password_enc", models.BinaryField(max_length=1000)),
                ("name_enc", models.BinaryField(max_length=1000)),
                (
                    "type",
                    models.CharField(
                        choices=[("free", "無料ユーザ"), ("pro", "Proユーザ")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "利用者ユーザ",
                "verbose_name_plural": "利用者ユーザ",
                "db_table": "users",
            },
            managers=[
                ("objects", user.models.user.UserManager()),
            ],
        ),
    ]
