# Generated by Django 4.2.21 on 2025-05-21 04:33

from django.db import migrations, models, transaction
import django.db.models.deletion
import user.models.demo_user
from user.models import User, AdminUser, DemoUser


def forwards_demo_user(apps, schema_editor):
    with transaction.atomic():
        for user in User.objects.all():
            if user.type != User.Type.PRO:
                continue

            child_type = DemoUser.ChildType.PRO
            demo_user = DemoUser.objects.create(
                child_type=child_type,
            )
            user.demo_user_ptr = demo_user
            user.child_type = child_type
            user.save()

        for admin_user in AdminUser.objects.all():
            child_type = (
                DemoUser.ChildType.ADMIN
                if admin_user.type == AdminUser.Type.ADMIN
                else DemoUser.ChildType.CONTRACTOR
            )
            demo_user = DemoUser.objects.create(child_type=child_type)
            admin_user.demo_user_ptr = demo_user
            admin_user.child_type = child_type
            admin_user.save()


def reverse_demo_user(apps, schema_editor):
    with transaction.atomic():
        User.objects.update(demo_user_ptr=None)
        AdminUser.objects.update(demo_user_ptr=None)


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "child_type",
                    models.CharField(
                        choices=[
                            ("pro", "Proユーザ"),
                            ("admin", "管理者"),
                            ("contractor", "法人契約者"),
                            ("other", "その他"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "認証用ユーザ",
                "verbose_name_plural": "認証用ユーザ",
                "db_table": "demo_users",
            },
            managers=[
                ("objects", user.models.demo_user.DemoUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="adminuser",
            managers=[
                ("objects", user.models.demo_user.DemoUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.demo_user.DemoUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="id",
            field=models.BigAutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="adminuser",
            old_name="id",
            new_name="child_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                db_column="id", primary_key=True, serialize=False
            ),
        ),
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="child_id",
        ),
        migrations.RemoveField(
            model_name="adminuser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AddField(
            model_name="adminuser",
            name="demo_user_ptr",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="admin_user",
                to="user.demouser",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="demo_user_ptr",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="user",
                to="user.demouser",
            ),
        ),
        migrations.RunPython(forwards_demo_user, reverse_demo_user),
    ]
